# 모집단과 표본
- 모집단: 추측하고 싶은 고나측 대상
- 표본: 추측에 사용하는 관측 대상의 일부분
- 표본통계량: 표본을 바탕으로 계산한 평균이나 분산, 상관계수 등
- 모수: 모집단의 평균, 분산, 상관계수 등

---

4.1.1
- 임의로 표본을 추출하는 방법: 무작위추출
 - 하지만, 무작위추출도 편향이 있는 데이터를 얻을 수 있음
- 복원추출 vs 비복원추출: 동일한 표본을 한번만 할지 말지로 결정

In [10]:
import numpy as np
np.random.choice([1,2,3],3)

array([1, 3, 3])

np.random.choice 는 기본적으로 복원추출로 수행

In [14]:
np.random.choice([1,2,3],3,replace=False)

array([3, 1, 2])

In [15]:
np.random.seed(0)
np.random.choice([1,2,3],3)

array([1, 2, 1])

시드 설정시, 동일한 난수 얻기 가능

In [24]:
import pandas as pd
df = pd.read_csv('data/ch4_scores400.csv') # 학생 예시 Score
scores  = np.array(df['score'])

In [27]:
np.random.seed(0)
sample = np.random.choice(scores,20)
sample.mean()

70.4

모평균을 구해보자.

In [29]:
scores.mean()

69.53

무작위추출과 그에 따른 표본평균 계산을 몇 번 실행해보자.

In [30]:
for i in range(5):
    sample = np.random.choice(scores,20)
    print(f'{i+1}번째 무작위추출로 얻은 표본평균',sample.mean())

1번째 무작위추출로 얻은 표본평균 72.45
2번째 무작위추출로 얻은 표본평균 63.7
3번째 무작위추출로 얻은 표본평균 66.05
4번째 무작위추출로 얻은 표본평균 71.7
5번째 무작위추출로 얻은 표본평균 74.15


표본평균은 대체로 70점 전후이지만, 나름대로 산포도를 나타내고 있음.